"""empty message

Revision ID: 762b5ad7c782
Revises: c6538b7a533b
Create Date: 2019-07-30 22:34:26.038401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762b5ad7c782'
down_revision = 'c6538b7a533b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
